---
- name: modprobe
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ kernel_modules }}"

- name: modprobe permanent
  template:
    src: modprobe
    dest: /etc/modules-load.d/kubeadm-modules.conf
    mode: '644'

- name: sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: install dependencies
  ansible.builtin.apt:
    name: ['nfs-common']
    update_cache: yes
  with_items:
    - curl
    - gnupg2
    - software-properties-common
    - apt-transport-https
    - ca-certificates
    - nfs-common

- name: install containerd
  ansible.builtin.unarchive:
    src: https://github.com/containerd/containerd/releases/download/v1.6.9/cri-containerd-1.6.9-linux-amd64.tar.gz
    dest: /
    remote_src: yes

- name: mkdir
  file:
    path: "{{ item }}"
    state: directory
  with_items:
    - /etc/containerd

- name: copy containerd config
  ansible.builtin.template:
    src: containerd.config.toml
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: enable containerd service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: containerd

# - name: install cni plugin
#   ansible.builtin.unarchive:
#     src: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
#     dest: /opt/cni/bin
#     remote_src: yes


- name: add kubeadm key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add kubeadm repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: install kubeadm
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    allow_downgrade: yes
  with_items:
    - kubeadm=1.24.7-00
    - kubelet=1.24.7-00
