---
- name: modprobe
  community.general.modprobe:
    name: "{{ item }}"
    state: present
  with_items: "{{ kernel_modules }}"

- name: modprobe permanent
  template:
    src: modprobe
    dest: /etc/modules-load.d/kubeadm-modules.conf
    mode: '644'

- name: sysctl
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: '1'
  with_items:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables
    - net.ipv4.ip_forward

- name: install dependencies
  ansible.builtin.apt:
    update_cache: yes
    pkg:
      - curl
      - gnupg2
      - software-properties-common
      - apt-transport-https
      - ca-certificates
      - nfs-common

- name: containerd repo
  ansible.builtin.shell: |
    sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    sudo chmod a+r /etc/apt/keyrings/docker.asc
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
      $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
      sudo tee /etc/apt/sources.list.d/docker.list > /dev/null

- name: install containerd.io
  ansible.builtin.apt:
    update_cache: yes
    name: containerd.io

- name: mkdir
  file:
    path: /etc/containerd
    state: directory
     
- name: copy containerd config
  ansible.builtin.template:
    src: containerd.config.toml
    dest: /etc/containerd/config.toml
    mode: '0644'

- name: enable containerd service
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: containerd
    enabled: true

# - name: install cni plugin
#   ansible.builtin.unarchive:
#     src: https://github.com/containernetworking/plugins/releases/download/v1.1.1/cni-plugins-linux-amd64-v1.1.1.tgz
#     dest: /opt/cni/bin
#     remote_src: yes


- name: add kubeadm repo
  ansible.builtin.shell: |
    curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.29/deb/Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes
    echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.29/deb/ /' | sudo tee /etc/apt/sources.list.d/kubernetes.list

- name: install kubeadm
  ansible.builtin.apt:
    name: "{{ item }}"
    update_cache: yes
    allow_downgrade: yes
  with_items:
    - kubeadm=1.29.5-1.1
    - kubelet=1.29.5-1.1
