---
- name: set hostname
  hostname:
    name: '{{inventory_hostname}}'

- name: update hosts
  lineinfile:
    path: /etc/hosts
    line: '127.0.0.1 {{inventory_hostname}}'

- name: network bridge
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: 1

- name: Disable swap
  shell: swapoff -a

- name: Disable swap permanently
  systemd:
    name: dphys-swapfile
    state: stopped
    enabled: no

- name: set timezone
  timezone:
    name: Australia/Melbourne

- name: install docker
  shell: 'curl -sSL get.docker.com | sh'
  args:
    warn: false
    creates: /usr/bin/docker

- name: pi user to docker group
  user:
    name: pi
    append: yes
    groups: docker

- name: add kubeadm key
  apt_key:
    url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

- name: add kubeadm repo
  apt_repository:
    repo: deb http://apt.kubernetes.io/ kubernetes-xenial main

- name: install kubeadm
  apt:
    name: kubeadm
    update_cache: yes

- name: copy kubeadm conf
  when: inventory_hostname == 'kmaster'
  template:
    src: kubeadm_conf.yaml
    dest: /root/kubeadm_conf.yaml

