- name: add telegraf repo key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: absent

- name: add telegraf repo
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable
    state: absent

- name: install telegraf
  apt:
    name: telegraf
    update_cache: yes
    state: absent

