- name: add telegraf repo key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: add telegraf repo
  apt_repository:
    repo: deb https://repos.influxdata.com/ubuntu focal stable
    state: present

- name: install telegraf
  apt:
    name: telegraf
    update_cache: yes
    state: latest

- name: enable telegraf service
  service:
    name: telegraf
    enabled: yes
    state: started

- name: update telegraf configuration
  lineinfile:
    path: /etc/telegraf/telegraf.conf
    line: '  urls = ["http://192.168.1.51:8086"]'
    firstmatch: yes
    insertafter: '^\[\[outputs.influxdb\]\]'
  notify:
    - reload telegraf

- name: enable network io
  lineinfile:
    path: /etc/telegraf/telegraf.conf
    line: '[[inputs.net]]'
    regexp: '^# \[\[inputs\.net\]\]'
  notify:
    - reload telegraf
